# Uncomment the next line to define a global platform for your project
  platform :ios, '11.0'

target 'Sample-SyncManager-iOS-swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Sample-SyncManager-iOS-swift
  pod 'SendBirdSyncManager'
  pod 'AlamofireImage'
  pod 'MGSwipeTableCell'
  pod 'FLAnimatedImage', '~> 1.0'
  pod 'NYTPhotoViewer', '~> 1.1.0'
  pod 'HTMLKit', '~> 2.1'
  pod 'TTTAttributedLabel'
  pod 'RSKImageCropper'
end
