# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SendBird-iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SendBird-iOS
  pod 'SendBirdSDK', '~> 3.0'
  pod 'MGSwipeTableCell'
  pod 'AFNetworking'
  pod 'FLAnimatedImage', '~> 1.0'
  pod 'NYTPhotoViewer', '~> 1.1.0'
  pod 'HTMLKit', '~> 2.0'
  pod 'TTTAttributedLabel'
  pod 'RSKImageCropper'
end
