# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod "SendBirdSDK", '~> 2.2'
pod "AFNetworking"

target 'SendBird Sample UI' do
  pod "SendBirdSDK", '~> 2.2'
  pod "AFNetworking"
end

target 'SendBirdSampleUITests' do
  pod "SendBirdSDK", '~> 2.2'
  pod "AFNetworking"
end

target 'SendBirdSampleUIUITests' do
  pod "SendBirdSDK", '~> 2.2'
  pod "AFNetworking"
end

