# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'SampleUI' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleUI
  pod 'SendBirdSDK'
  pod 'AlamofireImage', '~> 3.0'
  pod 'JSQMessagesViewController', :git => 'https://github.com/smilefam/JSQMessagesViewController.git'
end
